version: "3.9"

services:
  db:
    image: postgres:15
    container_name: task4_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_engineering_test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - task4_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - db
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    command: bash
    networks:
      - task4_network

volumes:
  db_data:

networks:
  task4_network:
    driver: bridge
