task_4_profile:
  outputs:
    dev:
      type: postgres
      host: db
      user: user
      password: password
      port: 5432
      dbname: data_engineering_test
      schema: public
  target: dev
